openapi: 3.0.0
info:
  title: Your API
  description: API for managing collections and contributions
  version: 1.0.0

paths:
  /api/v1/collections:
    get:
      tags:
        - Collections
      summary: Get a list of collections
      parameters:
        - in: query
          name: remaining_amount_min
          schema:
            type: number
          description: Remaining contribution amount min
        - in: query
          name: remaining_amount_max
          schema:
            type: number
          description: Remaining contribution amount max
        - in: query
          name: below_target
          schema:
            type: boolean
          description: Below target amount
      responses:
        '200':
          description: Successful response
    post:
      tags:
        - Collections
      summary: Create a new collection
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                target_amount:
                  type: integer
                link:
                  type: string
      responses:
        '201':
          description: Created
  /api/v1/collections/{id}:
    get:
      tags:
        - Collections
      summary: Get details of a collection
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
    put:
      tags:
        - Collections
      summary: Update a collection
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                target_amount:
                  type: integer
                link:
                  type: string
      responses:
        '200':
          description: Successful response
    delete:
      tags:
        - Collections
      summary: Delete a collection
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: No Content
  /api/v1/contributors:
    get:
      tags:
        - Contributors
      summary: Get a list of contributors
      responses:
        '200':
          description: Successful response
    post:
      tags:
        - Contributors
      summary: Create a new contributor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                collection_id:
                  type: integer
                user_name:
                  type: string
                  maxLength: 255
                amount:
                  type: number
                  minimum: 1
      responses:
        '201':
          description: Created

  /api/v1/contributors/{id}:
    get:
      tags:
        - Contributors
      summary: Get details of a contributor
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response

    put:
      tags:
        - Contributors
      summary: Update a contributor
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                email:
                  type: string
                contribution_amount:
                  type: number
      responses:
        '200':
          description: Successful response

    delete:
      tags:
        - Contributors
      summary: Delete a contributor
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: No Content
